// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpSvn3ciXk9132O8yj09OHoxzs-rgqb0',
    appId: '1:411167207929:web:851c10f15ebef8f20e8d28',
    messagingSenderId: '411167207929',
    projectId: 'kanda-3f009',
    authDomain: 'kanda-3f009.firebaseapp.com',
    storageBucket: 'kanda-3f009.appspot.com',
    measurementId: 'G-44X4RG2M98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3NGqDeyLaRBYitqM2YdeuEHFJx88jLQ',
    appId: '1:411167207929:android:121afc80d847d2ff0e8d28',
    messagingSenderId: '411167207929',
    projectId: 'kanda-3f009',
    storageBucket: 'kanda-3f009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCzFYZeKpgT2s0Jm9HgS5osRQTOEWR1GA',
    appId: '1:411167207929:ios:ecf3abd12ae117920e8d28',
    messagingSenderId: '411167207929',
    projectId: 'kanda-3f009',
    storageBucket: 'kanda-3f009.appspot.com',
    iosClientId: '411167207929-el1pf4otr0s27k4f3mnl9nflkng6qvs2.apps.googleusercontent.com',
    iosBundleId: 'com.github.kornosky.kanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCzFYZeKpgT2s0Jm9HgS5osRQTOEWR1GA',
    appId: '1:411167207929:ios:5d36d88df7ec15400e8d28',
    messagingSenderId: '411167207929',
    projectId: 'kanda-3f009',
    storageBucket: 'kanda-3f009.appspot.com',
    iosClientId: '411167207929-o71rtqaslub0qq5qajj4g66rsjja8psm.apps.googleusercontent.com',
    iosBundleId: 'com.github.kornosky.kanda.RunnerTests',
  );
}
