name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - uses: dart-lang/setup-dart@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KANDA_3F009 }}
          projectId: your-firebase-project-id  # Replace with your Firebase project ID
